### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by shiv86** [jarias/generator-jhipster-ember#14]
Hi Julio - Selecting the following options gave me the error located below:

? (1/7) What is the base name of your application? testapp
? (2/7) What is your default Java package name? tes.com
? (3/7) What is your application storage engine? PostgreSQL
? (4/7) Generate EmberJS UI? No
? (5/7) Use Stormpath as authentication provider? No
? (6/7) Use docker? No
? (7/7) Are you deploying to Heroku? No

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by jarias** [comment]
Strange I will look into it, thanks for the report

**Comment by jarias** [comment]
Just committed a hotfix, I think the issue was that the UI deps task was invoke even if you didn't want the UI to be generated, did you have ember-cli installed?

Can you check if its working by cloning the repo and do an npm link, just to make sure before I do a release in NPM.

Thanks.

**Comment by shiv86** [comment]
Sure will try it in approx 8 hours (after I get home from work). However I did have ember cli installed. Also I encountered the same issue when I did generate the Ember JS UI  as well.

**Comment by shiv86** [comment]
Thanks that worked!

**Comment by jarias** [comment]
Great, I'm going to publish a new version tomorrow to NPM
