### ISSUE TITLE
Production Deployment

### ISSUE THREAD

**Issue by afedulov** [jarias/generator-jhipster-ember#18]
Could you please give a hint about the best practices to deploy a jhipster-ember app into production without having to run emberServer? So far I have tried to build it using "gradle emberBuild" and copying the content of the dist folder into my locally running apache-httpd server (runs on port 8080). When I try to log in, authentication requests are POSTed to 
http://localhost:8080/oauth/token and get 404 as an answer. Should there necesseraly be some OAuth sessions handling server installed separately?

**Comment by jarias** [comment]
The generated app is a Spring Boot Java application, so you just need to create the jar file, form the root of the project ```./gradlew build``` then ```java -jar build/libs/PROJECT_JAR_NAME.jar``` of course you can move that jar file to your prefer location.

The emberServer is just for local development. 

The Ember UI is embedded in the main jar file when you invoke ```./gradlew build```

Hope this makes sense.

**Comment by afedulov** [comment]
Thanks for the hint. The complication is that for the backend part of the project I had to switch to maven for a variety of reasons. Spring Boot Maven plugin unfortunately does not include dependencies defined as direct system jars, so getting this setup to work seems to be quite tricky. I was wondering, is it possible to use the same approach as in the original jhipster project by placing UI into the webapp directory? Why did you choose to go with the jar approach?

**Comment by jarias** [comment]
As long as the files are in META-INF/resources or any of the other paths spring boot uses for serving static content, it should work

**Comment by jarias** [comment]
The jar approach makes it simpler to deploy all your app needs in in that single jar, no need to figure tomcat or any other resources just the JVM and your set, similar approach is taken by Dropwizard, you can always change it to the standard war file deployment too.

**Comment by afedulov** [comment]
To be frank it came a bit as a surprise for me as well, but you can in fact launch Jhipster with embedded Tomcat by doing this:
`java -jar jhipster-0.0.1-SNAPSHOT.war `
( see http://jhipster.github.io/production.html)
I have just managed to get everything running by simply copying the dist folder into src/main/webapp prior to running `mvn package`

**Comment by jarias** [comment]
Cool didn't knew that either.
